name: Node CI

on: [push]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:3.2.0

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: install
        run: |
          yarn install --frozen-lockfile

      - name: test
        run: |
          yarn cypress-ci
        env:
          CI: true
        shell: bash
