name: Node CI

on: [push]

jobs:
  test-e2e:
    runs-on: ubuntu-16.04
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001

    strategy:
      matrix:
        cypress-version: ["current"]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: install
        run: |
          yarn install --frozen-lockfile

      - name: test
        run: |
          yarn cypress-ci
        env:
          CI: true
        shell: bash
